name: Test My Runner

on: [push]

jobs:
  test-my-server:
    # 关键修改：不再用 ubuntu-latest，而是用你自己的 Runner
    runs-on: test-0
    
    steps:
      - name: Check connection
        run: echo "This is running on my own linux machine!"