name: Kunlun Unit Test

on: [push, pull_request]

jobs:
  test-kunlun:
    runs-on: [self-hosted, test-0]
      # 2. 【关键】全局环境变量
      # 放在这里，整个 Job 的所有步骤（包括 checkout 和 pip）都会自动生效
    env:
      http_proxy: http://10.63.229.53:8891
      https_proxy: http://10.63.229.53:8891
      # 建议加上 no_proxy，防止连接本地服务或内网 git 出问题
      no_proxy: localhost,127.0.0.1,0.0.0.0,.baidu.com,.baidu-int.com
      # 显式指定 vLLM 编译目标，防止安装主库时因为它去瞎找 CUDA 驱动而报错
      VLLM_TARGET_DEVICE: empty 
    

    steps:
      # --- 第一步：全局激活环境 (最关键的一步) ---
      - name: Activate Conda Environment Globally
        run: |
          # 1. 定义你的环境 bin 目录 (根据您提供的信息)
          # 注意：Conda 环境的可执行文件都在 /bin 目录下，必须精确指向这里
          CONDA_BIN="/root/miniconda/envs/python310_torch25_cuda/bin"
          
          # 2. 【核心魔法】将这个路径写入 GITHUB_PATH
          # 这样后续所有 Step 里的 'python' 和 'pip' 命令都会默认用这个目录下的
          echo "$CONDA_BIN" >> $GITHUB_PATH
          
          # 3. (可选) 设置 CONDA_PREFIX 变量，有些编译脚本依赖这个
          echo "CONDA_PREFIX=/root/miniconda/envs/python310_torch25_cuda" >> $GITHUB_ENV

      # --- 第二步：验证激活是否成功 ---
      - name: Verify Activation
        run: |
          echo "Which python am I using?"
          which python
          # 输出必须是: /root/miniconda/envs/python310_torch25_cuda/bin/python
          
          echo "Python Version:"
          python --version
          # 输出必须是: Python 3.10.x

          echo "Check PIP location:"
          which pip
          # 输出必须是: .../bin/pip

      - name: Install pytest
        run: 
          python -m pip install pytest 
      # --- 第五阶段：运行测试 ---
      
      - name: Debug Directory Structure
        run: |
          echo "Current working directory:"
          pwd
          
          echo "Listing root files:"
          ls -F
          
          echo "Listing tests directory (if exists):"
          ls -F tests/ || echo "tests folder not found!"
          
          echo "Searching for test files:"
          find . -maxdepth 4 -name "test_*.py" | head -n 5
      # --- 第五步：运行测试 ---
      - name: Run Unit Test
        run: |
          xpu-smi || echo "Warning: xpu-smi failed"
          # 这里的 pytest 也会自动用 conda 环境里的
          pytest -v -s tests/ut